# Generated by Django 5.1.2 on 2025-05-07 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("grenade_class", "0001_initial"),
        ("maps", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lineup",
            fields=[
                ("grenade_id", models.AutoField(primary_key=True, serialize=False)),
                ("link_to_video", models.CharField(max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(null=True)),
                ("is_approved", models.BooleanField(default=False)),
                ("views", models.IntegerField(default=0)),
                ("preview_image_link", models.CharField(max_length=255, null=True)),
                (
                    "grenade_class_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grenade_class.grenadeclass",
                    ),
                ),
                (
                    "map_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="maps.map"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
