# Generated by Django 5.1.2 on 2025-05-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lineups", "migrations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineup",
            name="preview_image_link",
            field=models.ImageField(
                null=True, upload_to="lineups/", verbose_name="Фото"
            ),
        ),
    ]
