services:
    tg-frontend:
        container_name: tg-frontend
        build:
            context: ./tg-frontend
            dockerfile: dockerfile.dev
            args:
                - MODE=${MODE}
        volumes:
            - ./tg-frontend:/tg-frontend
            - ./tg-frontend/node_modules:/tg-frontend/node_modules
        env_file: ./.env
        environment:
            - VITE_BACKEND_URL=${VITE_BACKEND_URL}
            - HUSKY=${FRONTEND_LINTING:?Variable FRONTEND_LINTING is required}
            - NODE_ENV=${MODE:?Variable Mode is required}
            - VITE_IN_TG_ENVIRONMENT=${IN_TG_ENVIRONMENT}
            - VITE_TG_INIT_DATA=${TG_INIT_DATA}
        ports:
            - 8000:5173
        depends_on:
            - bot
            - backend
        command: sh ./run-server.sh

    admin-frontend:
        container_name: admin-frontend
        build:
            context: ./admin-frontend
            dockerfile: dockerfile.dev
        volumes:
            - ./admin-frontend:/admin-frontend
            - ./admin-frontend/node_modules:/admin-frontend/node_modules
        env_file: ./.env
        environment:
            - VITE_ADMIN_API_URL=${VITE_ADMIN_API_URL}
            - VITE_BACKEND_URL=${VITE_BACKEND_URL}
            - NODE_ENV=${MODE:?Variable Mode is required}
        ports:
            - 8001:8001
        depends_on:
            - backend
        command: sh ./run-server.sh

    backend:
        container_name: backend
        build:
            context: ./backend
            dockerfile: dockerfile.dev
        volumes:
            - ./backend:/backend
        ports:
            - 3000:8000
        env_file: ./.env
        environment:
            - BACKEND_SERVER=${VITE_BACKEND_URL}
            - SECRET_KEY=${SECRET_KEY}
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - TOKEN=${TOKEN}
            - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
            - REDIS_PASS=${REDIS_PASS}
        depends_on:
            - db
        command: sh ./run-server.sh

    db:
        container_name: postgres-db
        image: postgres:15-alpine
        restart: always
        env_file: ./.env
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - 5433:5432
        healthcheck:
            test: ["CMD", "-f", "http://localhost:5433"]
    redis:
        container_name: redis_db
        image: redis:alpine
        restart: always
        env_file: ./.env
        environment:
        - REDIS_PASSWORD=${REDIS_PASS}
        ports:
        - 6379:6379
        command: redis-server --requirepass ${REDIS_PASS}
        healthcheck:
            test: ["CMD", "redis-cli", "-a", "${REDIS_PASS}", "ping"]
            interval: 5s
            timeout: 30s
            retries: 3

    info-service:
        container_name: info-service
        image: swaggerapi/swagger-ui
        ports:
            - 9999:8080
        volumes:
            - ./info-service/swagger.yaml:/spec/swagger.yaml
        environment:
            SWAGGER_JSON: /spec/swagger.yaml

    bot:
        container_name: bot
        build:
            context: ./bot
        volumes:
            - ./bot:/bot
        env_file: ./.env
        environment:
            - TOKEN=${TOKEN}
            - WEB_APP_URL=${WEB_APP_URL}
    
