FROM python:3.13-alpine3.20
WORKDIR /backend
COPY . .
RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 8000
#CMD ["python", "manage.py", "runserver", "0.0.0.0:8000", "--noreload",]
CMD ["python","uvicorn", "backend.asgi:application", "--host", "0.0.0.0", "--port", "8000", "--reload"]