package db_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestInitialSchemaPreservesPublicIDColumns(t *testing.T) {
	content := readBackendFile(t, "migrations", "000001_initial_schema.up.sql")
	required := []string{
		"user_id integer generated by default as identity primary key",
		"map_id integer generated by default as identity primary key",
		"grenade_id integer generated by default as identity primary key",
		"grenade_class_id integer generated by default as identity primary key",
		"property_id integer generated by default as identity primary key",
		"id integer generated by default as identity primary key",
		"unique (tg_id)",
	}
	for _, text := range required {
		if !strings.Contains(strings.ToLower(content), text) {
			t.Fatalf("migration missing %q", text)
		}
	}
}

func TestInitialSchemaContainsCoreRelationshipConstraints(t *testing.T) {
	content := strings.ToLower(readBackendFile(t, "migrations", "000001_initial_schema.up.sql"))
	required := []string{
		"unique (user_id, grenade_id)",
		"primary key (property_id, grenade_id)",
		"check (status in ('open', 'approved', 'rejected', 'merged', 'closed'))",
		"check (code in ('superuser', 'base_admin', 'editor'))",
		"references lineups(grenade_id)",
		"references users(user_id)",
	}
	for _, text := range required {
		if !strings.Contains(content, text) {
			t.Fatalf("migration missing %q", text)
		}
	}
}

func TestInitialSchemaDownDropsTablesInReverseDependencyOrder(t *testing.T) {
	content := strings.ToLower(readBackendFile(t, "migrations", "000001_initial_schema.down.sql"))
	expectedOrder := []string{
		"comments",
		"pull_requests",
		"favorites",
		"lineup_properties",
		"properties",
		"lineups",
		"grenade_classes",
		"maps",
		"user_admin_roles",
		"admin_roles",
		"users",
	}
	lastIndex := -1
	for _, table := range expectedOrder {
		index := strings.Index(content, "drop table if exists "+table)
		if index == -1 {
			t.Fatalf("down migration missing drop for %s", table)
		}
		if index <= lastIndex {
			t.Fatalf("drop for %s appears out of dependency order", table)
		}
		lastIndex = index
	}
}

func TestSQLCConfigAndSeedQueryExist(t *testing.T) {
	config := readBackendFile(t, "sqlc.yaml")
	query := strings.ToLower(readBackendFile(t, "internal", "db", "query.sql"))
	for _, expected := range []string{
		`schema: "migrations"`,
		`queries: "internal/db/query.sql"`,
		`out: "internal/db/generated"`,
		`sql_package: "pgx/v5"`,
	} {
		if !strings.Contains(config, expected) {
			t.Fatalf("sqlc.yaml missing %s", expected)
		}
	}
	if !strings.Contains(query, "-- name: gethealthvalue :one") ||
		!strings.Contains(query, "select 1::int as value") {
		t.Fatalf("query.sql missing GetHealthValue seed query")
	}
}

func readBackendFile(t *testing.T, parts ...string) string {
	t.Helper()
	pathParts := append([]string{"..", ".."}, parts...)
	content, err := os.ReadFile(filepath.Join(pathParts...))
	if err != nil {
		t.Fatalf("read %s: %v", filepath.Join(parts...), err)
	}
	return string(content)
}
