# Generated by Django 5.1.2 on 2025-05-07 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=255, unique=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                ("avatar_url", models.CharField(blank=True, max_length=255, null=True)),
                ("steam_link", models.CharField(blank=True, max_length=255, null=True)),
                ("tg_id", models.IntegerField(blank=True, null=True)),
                ("is_banned", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AdminType",
            fields=[
                ("admin_type_id", models.AutoField(primary_key=True, serialize=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_base_admin", models.BooleanField(default=False)),
                ("is_editor", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Admins",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "admin_type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth_app.admintype",
                    ),
                ),
            ],
            options={
                "unique_together": {("user_id", "admin_type_id")},
            },
        ),
    ]
