# Generated by Django 5.1.2 on 2025-03-19 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminType",
            fields=[
                ("admin_type_id", models.AutoField(primary_key=True, serialize=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_base_admin", models.BooleanField(default=False)),
                ("is_editor", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="GrenadeClass",
            fields=[
                (
                    "grenade_class_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="LineupType",
            fields=[
                ("type_id", models.AutoField(primary_key=True, serialize=False)),
                ("key_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="LineupTypeValues",
            fields=[
                ("value_id", models.AutoField(primary_key=True, serialize=False)),
                ("value", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Map",
            fields=[
                ("map_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("link", models.CharField(max_length=255)),
                ("image_link", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=255)),
                ("avatar_url", models.CharField(max_length=255)),
                ("steam_link", models.CharField(max_length=255)),
                ("tg_id", models.IntegerField()),
                ("email", models.EmailField(max_length=255)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("is_banned", models.BooleanField(default=False)),
                ("password", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Lineup",
            fields=[
                ("grenade_id", models.AutoField(primary_key=True, serialize=False)),
                ("link_to_video", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("approved", models.BooleanField(default=False)),
                ("views", models.IntegerField(default=0)),
                ("preview_image_link", models.CharField(max_length=255)),
                (
                    "grenade_class_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth_app.grenadeclass",
                    ),
                ),
                (
                    "type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth_app.lineuptype",
                    ),
                ),
                (
                    "map_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth_app.map"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth_app.user"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="lineuptype",
            name="value_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="auth_app.lineuptypevalues",
            ),
        ),
        migrations.CreateModel(
            name="Favorites",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "grenade_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth_app.lineup",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth_app.user"
                    ),
                ),
            ],
            options={
                "unique_together": {("user_id", "grenade_id")},
            },
        ),
        migrations.CreateModel(
            name="Admins",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "admin_type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth_app.admintype",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth_app.user"
                    ),
                ),
            ],
            options={
                "unique_together": {("user_id", "admin_type_id")},
            },
        ),
    ]
