# Generated by Django 5.1.2 on 2025-03-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0004_user_email_user_last_login_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="tg_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
