# Generated by Django 5.1.2 on 2025-04-09 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0006_create_mock_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                ("property_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="lineuptype",
            name="value_id",
        ),
        migrations.RemoveField(
            model_name="lineup",
            name="type_id",
        ),
        migrations.AddField(
            model_name="grenadeclass",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="grenadeclass",
            name="price",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="PropertyList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grenade_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth_app.lineup",
                    ),
                ),
                (
                    "key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth_app.property",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="LineupTypeValues",
        ),
        migrations.DeleteModel(
            name="LineupType",
        ),
    ]
