# Generated by Django 5.1.2 on 2025-04-11 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0007_property_remove_lineuptype_value_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lineup",
            old_name="approved",
            new_name="is_approved",
        ),
    ]
