# Generated by Django 5.1.2 on 2025-04-11 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0008_rename_approved_lineup_is_approved"),
    ]

    operations = [
        migrations.RenameField(
            model_name="propertylist",
            old_name="key",
            new_name="property_id",
        ),
    ]
