# Generated by Django 5.1.2 on 2025-04-11 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0009_rename_key_propertylist_property_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="propertylist",
            unique_together={("property_id", "grenade_id")},
        ),
    ]
