# Generated by Django 5.1.2 on 2025-04-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0010_alter_propertylist_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="value",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
