# Generated by Django 5.1.2 on 2025-04-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0011_property_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineup",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="lineup",
            name="link_to_video",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="lineup",
            name="preview_image_link",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="map",
            name="image_link",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="map",
            name="link",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
