FROM node:22-alpine AS build

WORKDIR /admin-frontend

COPY package*.json ./
RUN npm ci --no-audit --no-fund

COPY . .
RUN npm run build

FROM nginx:stable-alpine3.20-perl AS deploy

COPY --from=build /admin-frontend/dist/ /usr/share/nginx/html/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
