# Generated by Django 5.1.2 on 2025-05-07 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lineups", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                ("property_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PropertyList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grenade_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lineups.lineup"
                    ),
                ),
                (
                    "property_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "unique_together": {("property_id", "grenade_id")},
            },
        ),
    ]
