FROM node:22
ARG BACKEND_URL

ENV VITE_BACKEND_URL=$BACKEND_URL
ENV NODE_ENV production
ENV HUSKY 0

WORKDIR /tg-frontend

COPY package.json ./
COPY package-lock.json ./
RUN npm i

COPY . ./

RUN npm run build
