FROM node:22 AS builder
ARG BACKEND_URL

ENV IN_TG_ENVIRONMENT=true
ENV VITE_BACKEND_URL=$BACKEND_URL
ENV NODE_ENV production
ENV HUSKY 0

WORKDIR /tg-frontend/

COPY package.json ./
COPY package-lock.json ./
RUN npm i

COPY . ./

RUN npm run build

# Deploy stage
FROM nginx:stable-alpine3.20-perl AS deploy

COPY --from=builder /tg-frontend/dist/ /usr/share/nginx/html/

EXPOSE 443 80

CMD ["nginx", "-g", "daemon off;"]