FROM node:22 AS builder
ENV NODE_ENV production
ENV HUSKY 0

WORKDIR /tg-frontend

COPY package.json .
COPY package-lock.json .
RUN npm i

COPY . .

RUN npm run build

# ------------------------------------
FROM nginx:stable-alpine3.20-perl as production
ENV NODE_ENV production

COPY --from=builder /tg-frontend/dist /usr/share/nginx/html

# COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
