FROM node:22 as builder
ENV NODE_ENV development

WORKDIR /tg-frontend
COPY package*.json /tg-frontend

RUN npm install

COPY . /tg-frontend

EXPOSE 8080

CMD [ "npm", "install", "&&", "npm", "run", "host"]