create table users (
    user_id integer generated by default as identity primary key,
    username text not null unique,
    email text unique,
    password_hash text,
    first_name text,
    last_name text,
    avatar_url text,
    steam_link text,
    tg_id bigint,
    is_banned boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint users_tg_id_key unique (tg_id)
);

create table admin_roles (
    role_id integer generated by default as identity primary key,
    code text not null unique check (code in ('superuser', 'base_admin', 'editor')),
    created_at timestamptz not null default now()
);

create table user_admin_roles (
    user_id integer not null references users(user_id) on delete cascade,
    role_id integer not null references admin_roles(role_id) on delete cascade,
    created_at timestamptz not null default now(),
    primary key (user_id, role_id)
);

create table maps (
    map_id integer generated by default as identity primary key,
    name text not null,
    link text,
    is_esports_pool boolean not null default false,
    image_path text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table grenade_classes (
    grenade_class_id integer generated by default as identity primary key,
    name text not null,
    description text,
    price integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table lineups (
    grenade_id integer generated by default as identity primary key,
    map_id integer not null references maps(map_id) on delete cascade,
    user_id integer not null references users(user_id) on delete cascade,
    grenade_class_id integer not null references grenade_classes(grenade_class_id) on delete restrict,
    link_to_video text,
    title text not null,
    description text,
    is_approved boolean not null default false,
    views integer not null default 0,
    preview_image_path text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table properties (
    property_id integer generated by default as identity primary key,
    name text not null,
    value text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table lineup_properties (
    property_id integer not null references properties(property_id) on delete cascade,
    grenade_id integer not null references lineups(grenade_id) on delete cascade,
    created_at timestamptz not null default now(),
    primary key (property_id, grenade_id)
);

create table favorites (
    user_id integer not null references users(user_id) on delete cascade,
    grenade_id integer not null references lineups(grenade_id) on delete cascade,
    created_at timestamptz not null default now(),
    primary key (user_id, grenade_id),
    constraint favorites_user_grenade_key unique (user_id, grenade_id)
);

create table pull_requests (
    id integer generated by default as identity primary key,
    lineup_id integer not null references lineups(grenade_id) on delete cascade,
    creator_id integer not null references users(user_id) on delete cascade,
    approver_id integer references users(user_id) on delete set null,
    status text not null default 'OPEN' check (status in ('OPEN', 'APPROVED', 'REJECTED', 'MERGED', 'CLOSED')),
    created_at timestamptz not null default now(),
    closed_at timestamptz
);

create table comments (
    id integer generated by default as identity primary key,
    pull_request_id integer not null references pull_requests(id) on delete cascade,
    author_id integer not null references users(user_id) on delete cascade,
    text text not null,
    created_at timestamptz not null default now()
);

create index maps_name_idx on maps (lower(name));
create index lineups_map_id_idx on lineups (map_id);
create index lineups_user_id_idx on lineups (user_id);
create index lineups_is_approved_idx on lineups (is_approved);
create index lineups_title_idx on lineups (lower(title));
create index pull_requests_lineup_id_idx on pull_requests (lineup_id);
create index pull_requests_status_idx on pull_requests (status);
create index comments_pull_request_created_idx on comments (pull_request_id, created_at);

insert into admin_roles (role_id, code) values
    (1, 'superuser'),
    (2, 'base_admin'),
    (3, 'editor');
