FROM node:22 as builder
ARG BACKEND_URL

ENV VITE_BACKEND_URL=$BACKEND_URL
ENV NODE_ENV production
ENV HUSKY 0

WORKDIR /tg-frontend

COPY ../tg-frontend/package.json ./
COPY ../tg-frontend/package-lock.json ./
RUN npm i

COPY ../tg-frontend/ ./

RUN npm run build


FROM nginx:stable-alpine3.20-perl as production

COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /tg-frontend/dist /usr/share/nginx/html

EXPOSE 443 80

CMD ["nginx", "-g", "daemon off;"]