# Generated by Django 5.1.2 on 2025-05-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Map",
            fields=[
                ("map_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("link", models.CharField(max_length=255, null=True)),
                ("image_link", models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
