# Generated by Django 5.1.2 on 2025-05-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="map",
            name="image_link",
            field=models.ImageField(null=True, upload_to="maps/", verbose_name="Фото"),
        ),
    ]
