# Generated by Django 5.1.2 on 2025-05-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0002_alter_map_image_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="map",
            name="is_esports_pool",
            field=models.BooleanField(
                default=False, verbose_name="Есть ли в пуле фейсита/турниров"
            ),
        ),
    ]
